project:
  type: website
  output-dir: "docs"

website:
    title: "Tchiowa imagiologia 7/24"
    description: "Blog sobre Imagiologia Médica Geral de Cabinda em Angola"
    open-graph: true
    twitter-card: true
    page-navigation: true
    back-to-top-navigation: true
    navbar:
      search: true
      #logo:  "HGC_logotipo.png"  #assets/images/HGC_logotipo.png
      left:
        - icon: house-fill
          text: "Home"
          file: index.qmd
        - text: "Blog"
          file: blog.qmd
        - text: "Publicações"
          file: publication.qmd
      right:
        - text: "Sobre mim"
          file: about.qmd
          menu:
            - text: Source Code
              href: https://code.com
            - text: Report a Bug
              href: https://bugs.com
        - icon: github
          href: https://github.com/
        - icon: twitter
          href: https://twitter.com
        - icon: rss
          href: index.xml # lien vers le flux RSS
rss: true
format:
  html:
    theme:
      light: quartz
      dark: darkly
    css:
      - styles.css
    lang: pt
    date-format: 'dddd[, the] Do [of] MMMM, YYYY'
    highlight-style: github-dark
    meta:
      viewport: "width=device-width, initial-scale=1"

